### ISSUE TITLE
Generated QR code not recognized

### ISSUE THREAD

**Issue by sindrig** [vippsas/vipps-ecom-api#219]
I've generated a QR code following the instructions. The JWT in the url seems correct and the url in the token redirects to the correct url. However, the Vipps MT app fails to scan it:

![image](https://user-images.githubusercontent.com/683742/160726473-eabf42a7-ce7d-4fb1-86dd-d947a1d9d3ad.png)

Curiously, the app also fails to scan the example QR code here: https://github.com/vippsas/vipps-developers#vipps-demo-store

The generated QR code can be accessed here: https://qr-generator-mt-app-service.azurewebsites.net/qr-generator/v1?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmb3JtYXQiOiJpbWFnZS9wbmciLCJzaXplIjoiODAwIiwidXJsIjoiaHR0cHM6Ly9xci1tdC52aXBwcy5uby9yL0RJNWJqTkEwIiwiaXNzIjoiUXItQXBpIiwibmJmIjoxNjQ4NTk4NzA5LCJleHAiOjE2NDg2MDIzMDksImlhdCI6MTY0ODU5ODcwOX0.vwP1J0Cq7N3737DiHJmDncgrquiBsW9sVGX0ck2QYVA

**Comment by kaffikaffi** [comment]
Previously there has been som trouble with scanning QRs in the MT environment, they are fixed now, and I can't mange to reproduce a similar error with other redirect urls. I think the issue might be caused by the page you are trying to redirect to, because I get this error when i try to open it in chrome directly @sindrig 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/35420892/161707126-21c43448-8d78-4b2b-b289-d271bbebadae.png">

**Comment by sindrig** [comment]
I'm not able to generate a QR code right now. I don't believe the chrome error you're getting is related to this issue. The link to the QR code I pasted has of course expired so it won't generate an image.

I still get the same error when I scan the QR code here: https://github.com/vippsas/vipps-developers#vipps-demo-store

**Comment by kaffikaffi** [comment]
The reason why you can't generate the QR with the same url, is because the token in the url is expired. If you want to fetch the image of the QR again, you will have to send a `get` request with the id of that specific QR (or use the getAll endpoint), and you will receive a url with an updated token.

The demo-store QR you are referring to is not going to work with the MT-app, but it works with the prod app, due to environment specific reasons. I will add a heads up about that in the readme, thanks!

I would try to get the url again and test with the MT-app. I Have tried several times to reproduce the issue, but it seems like everything works for me. @sindrig

**Comment by sindrig** [comment]
```
The reason why you can't generate the QR with the same url, is because the token in the url is expired. If you want to fetch the image of the QR again, you will have to send a get request with the id of that specific QR (or use the getAll endpoint), and you will receive a url with an updated token.
```
I know, I said as much in the previous reply ;)

I realize that the QR code contains a redirect url that points to my custom url. In my case it's a ngrok tunnel to my local machine, and if some google phishing warning is stopping that from working with the app I'd say that's a problem with the app. 

The redirect url in question is https://qr-mt.vipps.no/r/qfpx9tVX. Chrome does indeed flag it as a deceptive site. curling it works though:

```
sindri->~$ curl -XGET -I https://qr-mt.vipps.no/r/qfpx9tVX
HTTP/2 302
date: Tue, 05 Apr 2022 22:20:39 GMT
content-length: 0
location: https://8bea-46-22-103-144.ngrok.io/sp/v2/vipps/grouptag1
```

I have also created a QR code that points to https://example.com, but it fails in the app with the same error.

The full code I'm using (with redacted secrets) is here. Also, if you could attach a QR code that should work in the MT app, could you share it with me to see if it scans on my phone?

```
#!/usr/bin/env bash

set -euo pipefail
subscription_key="..."
client_id="..."
client_secret="..."

id="$1"
url="$2"

at=$(curl -XPOST https://apitest.vipps.no/accessToken/get \
    -H "client_id: $client_id" \
    -H "client_secret: $client_secret" \
    -H "Ocp-Apim-Subscription-Key: $subscription_key" \
    -d '' | jq -r '.access_token')

if [[ "$url" == "get" ]]; then
    curl -XGET https://apitest.vipps.no/qr/v1/merchantRedirect \
        -H "Authorization: Bearer $at" \
        -H "Ocp-Apim-Subscription-Key: $subscription_key" \
        -H "Accept: image/png" \
        -H 'Content-Type: application/json'
else
    curl -XPOST https://apitest.vipps.no/qr/v1/merchantRedirect \
        -H "Authorization: Bearer $at" \
        -H "Ocp-Apim-Subscription-Key: $subscription_key" \
        -H "Accept: image/png" \
        -H 'Content-Type: application/json' \
        -d '{"id": "'"$id"'", "redirectUrl": "'"$url"'"}'
fi


```

**Comment by kaffikaffi** [comment]
Your implementations of the apis look correct. And you are correct with the ngrok tunnel as well, I tested with QR for that, and it should work 🤔 

Hmm, this is really weird. I can verify that the https://example.com QR  you posted works with my phones. So i struggle with reproducing the error, except when i try to scan it with the prod app, but that is expected. What MT-app version do you use? And what device do you use? You can find the version by going to `profile > about vipps > Version`

I generated a QR as well, which points to the demo-store in the MT environment, so you can test that also. 
<img width="847" alt="image" src="https://user-images.githubusercontent.com/35420892/161925148-225b7604-6056-49d2-8889-baecb0714bec.png">

**Comment by sindrig** [comment]
Interesting, your QR code doesn't scan either. The "Version Name" is `2.115.3-MT`, the Version Code is "718".

**Comment by kaffikaffi** [comment]
I see you are using an older version of the MT-app, could you try updating and see if that helps?

**Comment by sindrig** [comment]
That was it. Updated the app and scanning my QR codes works now. Thanks for the help @kaffikaffi!
